export const ActionTypes = {
    FETCH_ALL_PRODUCTS : 'FETCH_ALL_PRODUCTS',
    UPLOAD_IMAGE : 'UPLOAD_IMAGE',
    UPLOAD_THUMB_IMAGE : 'UPLOAD_THUMB_IMAGE',
    FETCH_ONE_PRODUCT : 'FETCH_ONE_PRODUCT'
}